[tool.black]
# https://github.com/psf/black
target-version = ["py39"]
line-length = 80
color = true

include = '\.py$'

exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.yaml
    | \.toml
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
    | data

)/
'''

[tool.ruff]
# Decrease the maximum line length to 79 characters.
line-length = 80